# Site settings
title: 97115104's blog
author: 97115104
email: x@97115104.com
description: A simple, content-focused blog detailing musings.
baseurl: ""  # IMPORTANT: This must match your GitHub repository name
url: "https://97115104.com"
github_username: antimoloch007
permalink: /:year/:month/:day/:title/
copyright-company: Austin Harshberger (97115104)

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Collections
collections:
  categories:
    output: true
    permalink: /categories/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"