# Site settings
title: My Blog
email: 1@97104.de
description: A simple, content-focused blog detailing my musings.
baseurl: "/blog"  # IMPORTANT: This must match your GitHub repository name
url: "https://antimoloch007.github.io"
github_username: antimoloch007
permalink: /:year/:month/:day/:title/
copyright-company: Austin Harshberger

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Collections
collections:
  categories:
    output: true
    permalink: /categories/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"