# Site settings
title: My Blog
email: founder@status.health
description: A simple, content-focused blog detailing my amusings.
baseurl: ""
url: "https://antimoloch007.github.io"
github_username: antimoloch007
permalink: /:year/:month/:day/:title/

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Collections
collections:
  categories:
    output: true
    permalink: /categories/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"