# Site settings
title: My Blog
email: your-email@example.com
description: A simple, content-focused blog
baseurl: ""
url: "https://yourusername.github.io"
github_username: yourusername
permalink: /:year/:month/:day/:title/

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Collections
collections:
  categories:
    output: true
    permalink: /categories/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"